### ISSUE TITLE
Update PR template checklists so usage indicates required items

### ISSUE THREAD

**Issue by jsf9k** [cisagov/.github#1]
# 🚀 Feature Proposal #

I humbly suggest that in our pull request template we:

1. Change the checklist under the “Types of Changes” section to a bulleted list of suggested types, and leave it up to the PR creator to add/remove change types as needed.
1. Leave the checklist under the “Checklist” section, but add a comment requesting that the PR creator:
    * Remove items that are not appropriate
    * Add items that are appropriate but missing

I am happy to create a PR with these changes, but I wanted to get buy-in/suggestions/alternatives from the group before doing so.

## Motivation ##

Our pull request templates have lists of checkboxes in them, which means that the PRs appear [here](https://github.com/pulls?q=is%3Apr+assignee%3Ajsf9k+archived%3Afalse+is%3Aclosed), for example, with a little checklist icon and the text “X/Y”, where X is the number of checkboxes checked and Y is the total number of checkboxes.  In our PR template the intent is that you only check the checkboxes that apply to the PR being created, but GitHub is clearly interpreting the checkboxes as a list of things that _must all be done_.  Hence the little checklist icon and the text, which is misleading because it suggests there is more to do on the pull request when this is not the case.

I feel that the suggested changes in the previous section would allow us to avoid misleading information in PR summaries, and more importantly make the "Types of Changes" and "Checklist" sections more useful and informative.  We aren’t in general adding useful items to those lists; draft PRs should have some empty checkboxes under “Checklist”, for example, and sometimes we check no boxes in the "Types of Changes” section because none of the default options apply.

**Comment by mcdonnnj** [comment]
>     * Changes are limited to a single goal (no scope creep) - _we are all guilty of this!!!_

We probably need to remember that one in reviews as well honestly.

**Comment by jsf9k** [comment]
> > * Changes are limited to a single goal (no scope creep) - _we are all guilty of this!!!_
> 
> We probably need to remember that one in reviews as well honestly.

Very good point.  We'll have to work to keep each other honest.

**Comment by hillaryj** [comment]
Here's some changes I'd recommend; first is the raw, followed by the markup version:
```
# <!-- Use the title to describe PR changes in the imperative mood --> #

<!-- Follow the conventions of great Git commit messages from -->
<!-- https://chris.beams.io/posts/git-commit/ -->

## 🗣 Description ##

<!-- Describe the "what" of your changes in detail -->
<!-- To avoid scope creep, limit changes to a single goal -->

## 💭 Motivation and Context ##

<!-- Why is this change required? -->
<!-- What problem does this change solve? How did you solve it? -->
<!-- Link to any related issue(s) here to auto-close it on merge. -->

## 🧪 Testing ##

<!-- How did you test your changes? How could someone else test this PR? -->

<!-- Include details of your testing environment, and the tests you ran to -->
<!-- see how your change affects other areas of the code, etc. -->

## 📷 Screenshots ##

<!-- Remove this section and header if not needed -->

## 🚥 Types of Changes ##

<!-- What types of changes does your code introduce? -->
<!-- Add any relevant types and remove any that don't apply -->
<!-- Consider making a PR against the template for new types -->

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (causes existing functionality to change)
- Documentation change or update

## ✅ Checklist ##

<!-- Remove any of the following that do not apply. -->
<!-- Draft PRs should have several un-checked boxes still to go -->
<!-- If you're unsure about any of these, don't hesitate to ask. -->
<!-- We're here to help! -->

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Future todos are captured in issues and/or comments
- [ ] Added assignee and relevant labels
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document
- [ ] Code changes follow [cisagov code standards](https://github.com/cisagov/development-guide)
- [ ] Updated repo/project documentation to reflect changes in this PR
- [ ] Added tests to cover my changes
- [ ] All new and existing tests pass
```
#  #




## 🗣 Description ##




## 💭 Motivation and Context ##





## 🧪 Testing ##






## 📷 Screenshots ##



## 🚥 Types of Changes ##





- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (causes existing functionality to change)
- Documentation change or update

## ✅ Checklist ##






- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Future todos are captured in issues and/or comments
- [ ] Added assignee and relevant labels
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document
- [ ] Code changes follow [cisagov code standards](https://github.com/cisagov/development-guide)
- [ ] Updated repo/project documentation to reflect changes in this PR
- [ ] Added tests to cover my changes
- [ ] All new and existing tests pass
