### ISSUE TITLE
Consolidate and simplify issue templates

### ISSUE THREAD

**Issue by hillaryj** [cisagov/.github#5]
# 🚀 Feature Proposal

The issue templates we currently have are too specific to purposes that don't generally fit our usage. Let's simplify our issue templates down to:

- Issue template
- Story/Epic template

## Motivation

We're working on filing more issues for smaller tasks of work. To do this, let's make the issue process less cumbersome.

Plus, we want folks to file issues when they experience problems, and our Question template tells them to email us.

## Example

Refer to templates from cloud.gov for examples:
- [cloud-gov Issue template](https://github.com/cloud-gov/.github/blob/master/.github/ISSUE_TEMPLATE/issue.md)
- [cloud-gov Story template](https://github.com/cloud-gov/.github/blob/master/.github/ISSUE_TEMPLATE/story.md)

**Comment by mcdonnnj** [comment]
I think there is value in keeping a "Bug Report" issue template. I'd like to lock out blank issues to encourage outside contributors (and internal contributors) from avoiding the templates. The "Question" and "Regression Report" templates are never used, and the "Feature Proposal" template is definitely too narrow in scope.

**Comment by jsf9k** [comment]
Some thoughts I had:
* It may make sense to have separate bug/problem/doesn't work and idea/feature issue types.
* I feel strongly that we should associate as many "keywords" as is practical with our templates, to help folks know determine which is appropriate to use.  Non-devs may not grok features, but they know what an idea is.
* I suggest avoiding keywords such as "issue" or "improvement" that are too generic, e.g. a bugfix is an "improvement", as is an idea.
* The `SECURITY.md` file in cisagov/.github should be modified to mention reporting the bug to us in addition to the official CISA vulnerabilities channel.  I am concerned that if a vulnerability is reported _only_ to the official channel then it will not make its way to us in a timely manner.

**Comment by mcdonnnj** [comment]
I think it would be helpful to add a `QUESTIONS.md` or similar to the root of this repository which has links to common repos/topics etc. Then we can link it in the configuration for the Issue Chooser instead.

**Comment by hillaryj** [comment]
To add a bit from discussion on the PR: the new `config.yml` could be used to link directly to the Discussions or Wiki tabs instead of `.github`'s `QUESTIONS.md`. However, even a relative link unfortunately has drawbacks in repositories that don't have an associated Discussions or Wiki tab; so, we are linking to `QUESTIONS.md` to give people looking for help a starting point.

In repositories with Discussions or Wiki, we can override the `config.yml` defaults to link directly to that repository's resources.

**Comment by mcdonnnj** [comment]
If we override `config.yml`, we have to manually include everything. The existence of *anything* in `ISSUE_TEMPLATE` breaks inheritance of these defaults. Please see https://github.com/cisagov/cyhy_amis/pull/300, where I had to manually add these default templates because we added a project specific issue template.

**Comment by jsf9k** [comment]
> However, even a relative link unfortunately has drawbacks in repositories that don't have an associated Discussions or Wiki tab; so, we are linking to `QUESTIONS.md` to give people looking for help a starting point.
> 
> In repositories with Discussions or Wiki, we can override the `config.yml` defaults to link directly to that repository's resources.

We could write some language that says "look at the Discussions page (if it exists), the Wiki page (if it exists), or at QUESTIONS.md" with appropriate links.  Some links will be broken, but they will be project-specific.  I think with nicely-crafted language we could include the best of both worlds (relative links and QUESTIONS.md).

Just a thought.  I'm not too concerned about this point, although I hate the idea of having to copy over _all_ the templates just to change one little blurb.  If the templates change upstream then the local ones will not be updated.

**Comment by hillaryj** [comment]
So, the status in looking further is that:

- Relative links in the `config.yml` are not supported by GitHub
- The `QUESTIONS.md` link takes the user to the `.github` repo, so relative links wouldn't be helpful there either to target the Discussions and Wiki of the original repo

So, until and unless GitHub supports relative links in the `config.yml` file, the consolidated `QUESTIONS.md` is our best bet and I'll close this issue.

If anyone wants to update language in that file, feel free to submit a PR.
