### ISSUE TITLE
Please Provide me step by step installation process 

### ISSUE THREAD

**Issue by mr1112200** [cisagov/.github#51]
# Step by step installation process #

Please suggest me 

## Motivation and context ##

Why does this work belong in this project?

This would be useful because...

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by dav3r** [comment]
Closing as spam.
