### ISSUE TITLE
Issue with Ubuntu 20.04 LTS. 

### ISSUE THREAD

**Issue by AloneAndUnknown** [cisagov/.github#55]
# 🐛 Summary #

What's wrong? Please be specific.

## To reproduce ##

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:
Same issue with the other user who was using ubuntu 22.04. Can you run this on ubuntu 20.04. Thanks
```console

```

Add any screenshots of the problem here.

**Comment by mcdonnnj** [comment]
Closing this as the issue makes no sense in the context of this repository.
